import type { AgentDefinition, ResearchSource } from "@/lib/research-demo";

export type ReportExportFormat = "pdf" | "markdown" | "txt";

export type ResearchReportExport = {
  question: string;
  report: AgentDefinition;
  agents: AgentDefinition[];
  sources: ResearchSource[];
  generatedAt?: Date;
};

type ReportSection = {
  title: string;
  agent: AgentDefinition;
  includeHeadline?: boolean;
};

const PDF_PAGE_WIDTH = 595;
const PDF_PAGE_HEIGHT = 842;
const PDF_MARGIN_X = 64;
const PDF_TOP = 774;
const PDF_BOTTOM = 66;

export function downloadResearchReport(data: ResearchReportExport, format: ReportExportFormat) {
  const content = createResearchReport(data, format);
  const extension = format === "markdown" ? "md" : format;
  const mimeType =
    format === "pdf"
      ? "application/pdf"
      : format === "markdown"
        ? "text/markdown;charset=utf-8"
        : "text/plain;charset=utf-8";
  const blob = new Blob([content], { type: mimeType });
  const filename = createReportFilename(data.question, extension, data.generatedAt);
  const downloadUrl = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = downloadUrl;
  link.download = filename;
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  link.remove();

  window.setTimeout(() => URL.revokeObjectURL(downloadUrl), 1000);
}

export function createResearchReport(
  data: ResearchReportExport,
  format: ReportExportFormat,
): BlobPart {
  if (format === "pdf") {
    return createPdfReport(data);
  }

  if (format === "markdown") {
    return createMarkdownReport(data);
  }

  return createTextReport(data);
}

export function createReportFilename(question: string, extension: string, date = new Date()) {
  const safeQuestion = question
    .normalize("NFKD")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .slice(0, 56);
  const datePart = date.toISOString().slice(0, 10);
  const title = safeQuestion || "research";

  return `research-report-${title}-${datePart}.${extension}`;
}

function createMarkdownReport(data: ResearchReportExport) {
  const generatedAt = formatReportDate(data.generatedAt);
  const sections = getReportSections(data);
  const lines = [
    "# Research Report",
    "",
    "## Research Question",
    "",
    data.question.trim(),
    "",
    "## Date",
    "",
    generatedAt,
    "",
    "---",
    "",
  ];

  sections.forEach((section) => {
    lines.push(`## ${section.title}`, "");
    if (section.includeHeadline !== false) {
      lines.push(`### ${section.agent.headline}`, "");
    }
    lines.push(...section.agent.paragraphs, "");

    if (section.agent.findings.length > 0) {
      section.agent.findings.forEach((finding) => lines.push(`- ${finding.text}`));
      lines.push("");
    }
  });

  lines.push("## Sources", "");
  data.sources.forEach((source) => {
    lines.push(
      `${source.number}. [${source.title}](${source.url})`,
      `   ${source.publisher} - ${source.detail}`,
      "",
    );
  });

  lines.push("---", "", "Generated by INQUIRA", "");
  return lines.join("\n");
}

function createTextReport(data: ResearchReportExport) {
  const generatedAt = formatReportDate(data.generatedAt);
  const sections = getReportSections(data);
  const lines = [
    "INQUIRA",
    "",
    "Research Report",
    "",
    "Research Question:",
    data.question.trim(),
    "",
    "Date:",
    generatedAt,
    "",
    "----------------------------------------",
    "",
  ];

  sections.forEach((section) => {
    lines.push(section.title.toUpperCase(), "");
    if (section.includeHeadline !== false) {
      lines.push(section.agent.headline, "");
    }
    lines.push(...section.agent.paragraphs, "");

    if (section.agent.findings.length > 0) {
      section.agent.findings.forEach((finding) => lines.push(`- ${finding.text}`));
      lines.push("");
    }
  });

  lines.push("SOURCES", "");
  data.sources.forEach((source) => {
    lines.push(
      `${source.number}. ${source.title}`,
      source.publisher,
      source.detail,
      source.url,
      "",
    );
  });

  lines.push("----------------------------------------", "", "Generated by INQUIRA", "");
  return lines.join("\n");
}

function createPdfReport(data: ResearchReportExport) {
  const sections = getReportSections(data);
  const pdf = new PdfDocument();

  pdf.addHeader();
  pdf.addText("Research Report", "F2", 26, [0.08, 0.11, 0.16], 18);
  pdf.addText("Research Question", "F2", 9, [0.31, 0.35, 0.4], 22);
  pdf.addWrappedText(data.question.trim(), "F1", 12, [0.08, 0.11, 0.16], 17);
  pdf.addText(`Date: ${formatReportDate(data.generatedAt)}`, "F1", 10, [0.31, 0.35, 0.4], 18);
  pdf.addRule();

  sections.forEach((section) => {
    pdf.addSectionHeading(section.title);
    if (section.includeHeadline !== false) {
      pdf.addText(section.agent.headline, "F2", 14, [0.08, 0.11, 0.16], 17);
    }
    section.agent.paragraphs.forEach((paragraph) => {
      pdf.addWrappedText(paragraph, "F1", 11, [0.18, 0.21, 0.26], 16);
    });

    section.agent.findings.forEach((finding) => {
      pdf.addBullet(finding.text);
    });
  });

  pdf.addSectionHeading("Sources");
  data.sources.forEach((source) => {
    pdf.addText(`${source.number}  ${source.title}`, "F2", 11, [0.08, 0.11, 0.16], 15);
    pdf.addWrappedText(`${source.publisher} - ${source.detail}`, "F1", 10, [0.31, 0.35, 0.4], 14);
    pdf.addWrappedText(source.url, "F1", 9, [0.2, 0.34, 0.49], 14);
  });

  pdf.addRule();
  pdf.addText("Generated by INQUIRA", "F1", 9, [0.31, 0.35, 0.4], 0);

  return pdf.toBytes();
}

function getReportSections(data: ResearchReportExport): ReportSection[] {
  const analyst = data.agents.find((agent) => agent.id === "analyst");
  const critic = data.agents.find((agent) => agent.id === "critic");
  const sections: ReportSection[] = [{ title: "Executive Summary", agent: data.report }];

  if (data.report.findings.length > 0) {
    sections.push({
      title: "Key Findings",
      agent: { ...data.report, paragraphs: [] },
      includeHeadline: false,
    });
  }

  if (analyst) {
    sections.push({ title: "Research Analysis", agent: analyst });
  }

  if (critic) {
    sections.push({ title: "Critique / Validation", agent: critic });
  }

  return sections;
}

function formatReportDate(date = new Date()) {
  return new Intl.DateTimeFormat("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(date);
}

function normalizePdfText(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[^\x20-\x7E]/g, "");
}

function pdfText(value: string) {
  return normalizePdfText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(value: string, maxCharacters: number) {
  const words = normalizePdfText(value).split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";

  words.forEach((word) => {
    const nextLine = line ? `${line} ${word}` : word;
    if (nextLine.length > maxCharacters && line) {
      lines.push(line);
      line = word;
      return;
    }
    line = nextLine;
  });

  if (line) {
    lines.push(line);
  }

  return lines;
}

class PdfDocument {
  private pages: string[][] = [[]];
  private pageIndex = 0;
  private cursorY = PDF_TOP;

  addHeader() {
    this.addText("INQUIRA", "F2", 9, [0.08, 0.11, 0.16], 0);
    this.addRule();
  }

  addSectionHeading(value: string) {
    this.ensureSpace(42);
    this.addText(value.toUpperCase(), "F2", 10, [0.08, 0.11, 0.16], 14);
  }

  addBullet(value: string) {
    const lines = wrapText(value, 78);
    this.ensureSpace(lines.length * 15 + 8);
    this.addRawText("-", "F2", 10, [0.08, 0.11, 0.16], PDF_MARGIN_X, this.cursorY);
    lines.forEach((line, index) => {
      this.addRawText(line, "F1", 10, [0.18, 0.21, 0.26], PDF_MARGIN_X + 15, this.cursorY);
      this.cursorY -= 15;
      if (index === lines.length - 1) {
        this.cursorY -= 4;
      }
    });
  }

  addWrappedText(
    value: string,
    font: "F1" | "F2",
    size: number,
    color: [number, number, number],
    spacing: number,
  ) {
    const lines = wrapText(value, size >= 12 ? 78 : 90);
    this.ensureSpace(lines.length * spacing + 8);
    lines.forEach((line) => {
      this.addRawText(line, font, size, color, PDF_MARGIN_X, this.cursorY);
      this.cursorY -= spacing;
    });
    this.cursorY -= 5;
  }

  addText(
    value: string,
    font: "F1" | "F2",
    size: number,
    color: [number, number, number],
    spacing: number,
  ) {
    this.ensureSpace(Math.max(spacing, size + 4));
    this.addRawText(value, font, size, color, PDF_MARGIN_X, this.cursorY);
    this.cursorY -= spacing || size + 4;
  }

  addRule() {
    this.ensureSpace(20);
    this.currentPage().push(
      `${formatNumber(PDF_MARGIN_X)} ${formatNumber(this.cursorY)} m ${formatNumber(PDF_PAGE_WIDTH - PDF_MARGIN_X)} ${formatNumber(this.cursorY)} l 0.75 w 0.74 0.76 0.79 RG S`,
    );
    this.cursorY -= 22;
  }

  toBytes() {
    this.pages.forEach((page, index) => {
      page.push(
        `BT /F1 8 Tf 0.42 0.45 0.5 rg 1 0 0 1 ${PDF_MARGIN_X} 38 Tm (INQUIRA) Tj ET`,
        `BT /F1 8 Tf 0.42 0.45 0.5 rg 1 0 0 1 ${PDF_PAGE_WIDTH - PDF_MARGIN_X - 24} 38 Tm (${index + 1}) Tj ET`,
      );
    });

    return createPdfBytes(this.pages);
  }

  private addRawText(
    value: string,
    font: "F1" | "F2",
    size: number,
    color: [number, number, number],
    x: number,
    y: number,
  ) {
    const [red, green, blue] = color.map(formatNumber);
    this.currentPage().push(
      `BT /${font} ${formatNumber(size)} Tf ${red} ${green} ${blue} rg 1 0 0 1 ${formatNumber(x)} ${formatNumber(y)} Tm (${pdfText(value)}) Tj ET`,
    );
  }

  private ensureSpace(requiredHeight: number) {
    if (this.cursorY - requiredHeight >= PDF_BOTTOM) {
      return;
    }

    this.pages.push([]);
    this.pageIndex += 1;
    this.cursorY = PDF_TOP;
    this.addHeader();
  }

  private currentPage() {
    const page = this.pages[this.pageIndex];
    if (!page) {
      throw new Error("PDF page was not initialized.");
    }
    return page;
  }
}

function createPdfBytes(pages: string[][]) {
  const objects = new Map<number, string>();
  const pageObjectNumbers = pages.map((_, index) => 6 + index * 2);

  objects.set(1, "<< /Type /Catalog /Pages 2 0 R >>");
  objects.set(
    2,
    `<< /Type /Pages /Kids [${pageObjectNumbers.map((number) => `${number} 0 R`).join(" ")}] /Count ${pages.length} >>`,
  );
  objects.set(3, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  objects.set(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

  pages.forEach((commands, index) => {
    const contentObjectNumber = 5 + index * 2;
    const pageObjectNumber = 6 + index * 2;
    const stream = commands.join("\n");

    objects.set(
      contentObjectNumber,
      `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    );
    objects.set(
      pageObjectNumber,
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PDF_PAGE_WIDTH} ${PDF_PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObjectNumber} 0 R >>`,
    );
  });

  let document = "%PDF-1.4\n% INQUIRA\n";
  const offsets = [0];
  const highestObjectNumber = Math.max(...objects.keys());

  for (let objectNumber = 1; objectNumber <= highestObjectNumber; objectNumber += 1) {
    const object = objects.get(objectNumber);
    if (!object) {
      throw new Error(`PDF object ${objectNumber} was not created.`);
    }
    offsets[objectNumber] = document.length;
    document += `${objectNumber} 0 obj\n${object}\nendobj\n`;
  }

  const xrefOffset = document.length;
  document += `xref\n0 ${highestObjectNumber + 1}\n0000000000 65535 f \n`;

  for (let objectNumber = 1; objectNumber <= highestObjectNumber; objectNumber += 1) {
    document += `${String(offsets[objectNumber]).padStart(10, "0")} 00000 n \n`;
  }

  document += `trailer\n<< /Size ${highestObjectNumber + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return new TextEncoder().encode(document);
}

function formatNumber(value: number) {
  return Number(value.toFixed(3)).toString();
}
